---
- name: Install PostgreSQL
  become: yes
  yum:
    name: "postgresql-server"
    state: present
  tags:
    - postgresql

- service:
    name: postgresql
    state: initdb

- name: add bacula repo file
  template: src=bacula.repo.j2 dest=/etc/yum.repos.d/bacula.repo
  tags: bacula-sd

- name: install bacula-sd
  yum: name=bacula-enterprise-postgresql state=present
  tags: bacula-sd

- name: Enable services for automatic start
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - postgresql
    - bacula-sd

- service: name=postgresql state=started enabled=yes

- name: db init
  sudo_user: postgres
  command: /opt/bacula/scripts/create_postgresql_database
  command: /opt/bacula/scripts/make_postgresql_tables
  command: /opt/bacula/scripts/grant_postgresql_privileges
  command : exit

- service: name=bacula-sd state=stopped

- name: configure bacula-sd
  template: src=bacula-sd.conf.j2 dest=/opt/bacula/etc/bacula-sd.conf
  tags: bacula-sd

- service: name=bacula-sd state=started

- template: src=File.cfg.j2 dest=/opt/bacula/etc/conf.d/Director/bacula-dir/Storage/{{ sd_name }}-File.cfg
  delegate_to: "{{ groups['director'][0] }}"

- service: state=restarted name=bacula-director
  delegate_to: "{{ groups['director'][0] }}"

  