---
- hosts: bacula-client
  sudo: yes
  vars:
    dir_name: bacula-dir
    client_ip: {{ ansible_default_ipv4.address }}
    client_name: {{ ansible_hostname }}
    client_password:
  roles:
    - client